name: Node CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: reactJS unit test
        env:
          CI: false
          NODE_ENV: "development"
        run: |
          npm install
          CI=true npm run test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          CI: false
        run: |
          sudo npm install -g yarn
          yarn install
          yarn build
          git checkout gh-pages
          cp -r build/* .;
          git add .;
          git commit -am "staged deploy"
          git push origin gh-pages
          rm -r build
