name: Node CI

on:
  push:
    branches: [master]

jobs:
  # build:
  #   name: Build Checks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: reactJS unit test
  #       env:
  #         CI: false
  #         NODE_ENV: "development"
  #       run: |
  #         # npm install
  #         # CI=true npm run test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # needs: [build]
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
      - name: Deploy
        env:
          CI: false
        run: |
          sudo npm install -g yarn
          yarn install
          yarn build
          git config user.email "nimishshah2000@gmail.com"
          git config user.name "sudonims"
          git remote set-url --push origin https://sudonims:$GITHUB_TOKEN@github.com/sudonims/sudonims
          # git commit -am "build"
          git switch gh-pages
          shopt -s extglob
          rm -rf !("out"|"CNAME")
          cp -r out/. .;
          rm -r out
          touch .nojekyll
          git add .;
          git commit -am "staged deploy"
          git push origin gh-pages
